modLoader = "javafml" #//mandatory
loaderVersion = "*" # // mandatory. Allow all forge versions as we are definding what Minecraft versions we requre later on
license = "LGPL"
issueTrackerURL = "https://gitlab.com/distant-horizons-team/distant-horizons/-/issues"

# https://docs.neoforged.net/docs/gettingstarted/modfiles/#neoforgemodstoml


[[mods]] #//mandatory
    modId = "distanthorizons" #//mandatory
    version = "3.3.2" #//mandatory, gets the version number from jar populated by the build.gradle script
    displayName = "Distant Horizons" #//mandatory
    authors = ["James Seibel", "Leonardo Amato", "Cola", "coolGi", "Ran", "Leetom", "pshsh"] # Should be done with `["James Seibel", "Leonardo Amato", "Cola", "coolGi", "Ran", "Leetom", "pshsh"]`, but architectury complains
    #//updateJSONURL="https://change.me.example.invalid/updates.json" # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
    displayURL = "https://modrinth.com/mod/distanthorizons"
    description = "This mod generates and renders simplified terrain beyond the normal view distance at a low performance cost. Allowing you to see much farther without turning your game into a slideshow." #//mandatory. The description text for the mod
    logoFile = "assets/distanthorizons/logo.png"
    iconFile = "assets/distanthorizons/logo.png" #// needed for MC 26.3 and newer
    catalogueImageIcon = "assets/distanthorizons/icon.png"
    credits = "Massive thanks to all the developers for their hard work to bring Distant Horizons to where it is today. - James"
    #// if not set defaults to "false"
    clientSideOnly = "true"
    #// if not set side defaults to "CLIENT", "SERVER", "BOTH"
    side = "BOTH"
    #// Allow any version to be present (or not) on the server
    acceptableRemoteVersions = "*"

# We may need this to make forge (lexforge) & neoforge work together
[[mixins]]
    config = "DistantHorizons.neoforge.mixins.json"

[[dependencies.distanthorizons]]
    modId = "minecraft"
    type = "required"
    versionRange = "[26.3]" # Where we set what version of mc it is available for
    ordering = "NONE"
    side = "BOTH"

[[dependencies.distanthorizons]]
    modId = "neoforge"
    type = "required"
    versionRange = "[*,)" 
    ordering = "NONE"
    side = "BOTH"


