"""One-off source-data import. Does not build or touch installed user settings."""
import json
from pathlib import Path
from urllib.request import urlopen

COMMIT = "b16f532359d82ddb17cd0911a5d1420cb7560986"
URL = f"https://raw.githubusercontent.com/jacobsjo/snowcapped/{COMMIT}/src/main/Vanilla/VanillaSplines.ts"
ROOT = Path(__file__).resolve().parents[1]


def node(value):
    if isinstance(value, (float, int)):
        return value
    axis = {"weirdness": "weirdness", "ridges": "pv"}[value["coordinate"].split(":")[-1]]
    return {"axis": axis, "points": [
        {"location": p["location"], "derivative": p["derivative"], "value": node(p["value"])}
        for p in value["points"]]}


def grid(tree):
    rows = tree["points"]
    assert all(p["derivative"] == 0 for p in rows)
    coordinates = sorted({p["location"] for r in rows if isinstance(r["value"], dict)
                          for p in r["value"]["points"]})
    cells = []
    for row in rows:
        value = row["value"]
        if isinstance(value, (float, int)):
            cells.extend([value] + [None] * (len(coordinates) - 1))
            continue
        assert value["coordinate"].split(":")[-1] == "erosion"
        assert all(p["derivative"] == 0 for p in value["points"])
        lookup = {p["location"]: node(p["value"]) for p in value["points"]}
        cells.extend(lookup.get(e) for e in coordinates)
    return {"groundness": [p["location"] for p in rows], "smoothness": coordinates, "cells": cells}


def main():
    source = urlopen(URL, timeout=30).read().decode()
    preset = {"enabled": True, "height_scale": 128.0, "jagged_scale": 128.0, "jagged_enabled": True}
    for name in ("offset", "factor", "jaggedness"):
        start = source.index("{", source.index("public static " + name))
        tree, _ = json.JSONDecoder().raw_decode(source[start:])
        preset[name] = grid(tree)
    raw = json.dumps(preset, separators=(",", ":"))
    (ROOT / "src/world/terrain_preset.inc").write_text(
        f"// Generated by tools/import-terrain-preset.py from Snowcapped {COMMIT}.\n"
        "// Vanilla spline data: Mojang / Microsoft; see assets/worldgen/NOTICE.md.\n"
        'R"terrain(' + raw + ')terrain"\n', encoding="utf-8")
    path = ROOT / "assets/worldgen/default.json"
    config = json.loads(path.read_text(encoding="utf-8"))
    config["schema_version"] = 6
    config["squash"] = 0.2
    config.setdefault("domain_warp", dict(enabled=False, spacing_log2=10, strength=128.0))
    config["groundness"] = dict(spacing_log2=11, octaves=9, seed_offset=0,
                                 weights=[1, .5, .5, .25, .125, .03125, .015625, .0078125, .00390625])
    config["smoothness"] = dict(spacing_log2=11, octaves=5, seed_offset=30103, weights=[1, .5, 0, .125, .0625])
    config["weirdness"] = dict(spacing_log2=9, octaves=6, seed_offset=41507, weights=[1, 1, .25, 0, 0, 0])
    config["jagged"] = dict(spacing_log2=6, octaves=5, seed_offset=74929, gain=.5)
    config["splines"] = preset
    path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    print("Imported offset, factor, jaggedness; source assets only.")


if __name__ == "__main__":
    main()
